name: ESLint Prettier

on:
  push:
    tags:
      - '**'
    paths:
      - "trophoria-eslint/**"

  workflow_dispatch:

jobs:
  deploy_package:
    name: deploy eslint config
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./trophoria-eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
